project:
  type: website
  output-dir: docs

website:
  title: "My Data Science Blog"
  navbar:
    left:
      - text: "Home"
        href: pages/index.md
      - text: "Air Quality"
        href: pages/test.qmd
